### ISSUE TITLE
BackupEvent query not returning list of backup events

### ISSUE THREAD

**Issue by osandvold302** [bioneos/backup-system#11]
I believe this has something to do with gt not functioning how we expect.
``` 
where: {
      gt : lastSummaryDate
} 
```

The query this performs is 
```
SELECT `id`, `machine`, `rsyncExitCode`, `rsyncExitReason`, `transferSize`, `transferTimeSec`, `backupTime` FROM `BackupEvents` AS `BackupEvent` WHERE `BackupEvent`.`backupTime` = '2018-05-30 00:00:00.000 +00:00';
```

INSTEAD of `backupTime` > `'2018-05-30 00:00:00.000 +00:00'

**Comment by sgdavis1** [comment]
Yeah, I had copied that from existing code and it must have never gotten converted to the new Sequelize. That should read: 
```where: {
  [Op.gt] : lastSummaryDate
}```

**Comment by osandvold302** [comment]
to use Op.gt, you need to define Op = Sequelize.Op inside the file

**Comment by osandvold302** [comment]
required sequelize and defined Op using the above definition, this gets all of the backupEvents since lastSummaryDate. I also found a typo 'backupsEvents' instead of 'backupEvents' in the .then() function chained to the database promise
