### ISSUE TITLE
SMS implementation

### ISSUE THREAD

**Issue by sgdavis1** [bioneos/backup-system#13]
I'd like this system to be able to send SMS alerts. But it is FOSS, so I'd prefer to use a free service. I had tried implementing this with [textbelt](https://www.npmjs.com/package/textbelt) but it wasn't working for my carrier (Ting) although I am sure this would work for major carriers. I want to explore other options, as I would like to see this work as universally as possible.

Do a little research and propose the module or mechanism in this Issue for discussion before working on any implementation related to this.

**Comment by osandvold302** [comment]
There are several messaging services I have looked at but found that most of them are not free services. Twilo, on first look over, seems to be the superior SMS messaging paid service. The API is well maintained with options for various languages. The only free service I could find was textbelt, which as you mention, will work for most major carriers -

- USCC
- Alltel - AT&T, Verizon
- Sprint
- Cellular One
- Telus
- ACSWireless - Alaska
- PCS.Rogers
- Qwest
- Cricket
- Tmobile
- Windmobile

I have Verizon service, so I would be able to receive SMS alerts, but of course that would not be very beneficial long term for you.

**Comment by osandvold302** [comment]
After continuing research, I found that AWS SNS offers a free tier for worldwide SNS if the total number of messages is less than 100.

![aws_sns](https://user-images.githubusercontent.com/32017644/40855632-a568c682-659a-11e8-996b-8ad024638adb.png)

**Comment by osandvold302** [comment]
AWS SNS's sms pushing has been implemented as a feature in commit [0fe752e047d4ed3fb924c00eac337f7823baa1ee](https://github.com/bioneos/backup-system/commit/0fe752e047d4ed3fb924c00eac337f7823baa1ee). Read through README-SMS file to configure sms messaging.
