### ISSUE TITLE
Dependency management

### ISSUE THREAD

**Issue by sgdavis1** [bioneos/backup-system#16]
We currently have several outdated packages that we depend on, and should consider upgrading. These (sqlite3, fs-extra, gulp-sass) are major version updates. We will need to ensure that when these are upgraded, none of the code relying on these breaks due to any possible API changes.

Please upgrade the package.json file to allow these major version updates and then perform the upgrade and fully test it. Double check the documentation on those modules to see if we have to make any changes in our code to keep up with their best practices.

**Comment by sgdavis1** [comment]
Also while doing this, let's re-write our `package.json` to drop any patch level specified for better compatibility with what we intend. 

Ex] 
Change: `"sequelize": "^4.37.7"` to `"sequelize": "^4.37"`

**Comment by osandvold302** [comment]
The latest version of Gulp, 4.0.0, removes the list parameter syntax to define tasks and task dependencies. They have provided a boilerplate to model your project's gulpfile on -- [https://github.com/jh3y/gulp-boilerplate](https://github.com/jh3y/gulp-boilerplate). They also introduce series() and parallel() to clearly define dependencies and order of operations

**Comment by osandvold302** [comment]
Complete with dependencies branch merged into devel
