### ISSUE TITLE
Incorporate testing

### ISSUE THREAD

**Issue by sgdavis1** [bioneos/backup-system#17]
As per the assessment by @osandvold302 , we are going to incorporate testing using the [Jest](https://facebook.github.io/jest/) framework. Once we have some basic testing in place, she will merge this into `devel` and we will discuss goals for code coverage, code reorganization, etc.

**Comment by osandvold302** [comment]
This is complete with commit# d6d5dff1934f44fd8d98694e8ef9fd217125bc40
