### ISSUE TITLE
Incorporate more testing on backup processes

### ISSUE THREAD

**Issue by osandvold302** [bioneos/backup-system#18]
Specifically, the following processes I would like to test
- [x] getNextScheduledTime, needs to be rearranged first
- [x] Adding a backup event to the DB
- [x] Adding a process event to the DB
- [x] Getting events from DB before specified date

**Comment by osandvold302** [comment]
This is a little tricky, because I'm not sure how to develop a function within Jest to actually set up a temporary sqlite database

**Comment by DominicRutkowski** [comment]
We might be able to create a temporary database with [this method](https://www.sqlite.org/inmemorydb.html). I can test this, but it looks like all you have to do in Sequelize is make `options.storage` be `:memory:` in the Sequelize [constructor](http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html#instance-constructor-constructor).

**Comment by sgdavis1** [comment]
Setup a `tests/test.config.json` file to bypass the config parsing and automatically flag `app/models/index.js` to startup in memory mode (and use a different `data_dir`)

**Comment by DominicRutkowski** [comment]
https://github.com/bioneos/backup-system/commit/a83c8430e6cbe4f74ab9dd16e30e9b283b700f8a creates a temporary database in memory for unit tests. I only implemented one test in this branch, but I can add more over time as the temporary database is now ready to use.

**Comment by dominicrutk** [comment]
Tests added by https://github.com/bioneos/backup-system/commit/61581a4491ef41675c6a379d9576c1d722694091 as described by the above checklist. More tests could be added still, however.
