### ISSUE TITLE
Begin modernizing syntax

### ISSUE THREAD

**Issue by osandvold302** [bioneos/backup-system#21]
There are a couple things that need to be addressed when modernizing the syntax to ES6. 
- [ ] Big arrow notation in replace of anonymous functions
- [ ] Proper use of 'let' and 'const' in replace of 'var'

**Comment by sgdavis1** [comment]
How much of this has been completed thus far?

**Comment by osandvold302** [comment]
Three files left to remove 'var' from, system.js, init.js, and home.js.

**Comment by osandvold302** [comment]
Commit [c280eb](https://github.com/bioneos/backup-system/commit/c280eb7649dc623a29efedae3a55e048d3029152) removes the last `var` declarations from the codebase.
