### ISSUE TITLE
Restrict Multiple running instances

### ISSUE THREAD

**Issue by sgdavis1** [bioneos/backup-system#25]
Given the assumptions in the startup/shutdown database table alone (as I am sure there are other parts of the system that rely on only a single running instance exsting), we should come up with a way to restrict startup if the system is already running. Probably something simple like a lock file.

Probably something similar to [this](https://github.com/republicwireless-open/electron-single-instance) but not specific to electron.

This is a lower priority.

**Comment by DominicRutkowski** [comment]
Closed by https://github.com/bioneos/backup-system/commit/5fa372564a383b38121c4c4ca9714fffd03a6bf7
