### ISSUE TITLE
Logo and name

### ISSUE THREAD

**Issue by sgdavis1** [bioneos/backup-system#27]
I have thrown together some basics for a logo and suggested name. We need to finalize this and brand the web application.

**Comment by zuurritaly** [comment]
Hello @sgdavis1 , how are you?
Im a graaphic designer and I would like to help with the design of the logo for this project if you want, I 

Cheers
Zuur Willem

**Comment by sgdavis1** [comment]
I just recently added an initial suggestion (see the hidden back and up
arrow??) But would love some revision or other suggestions. Why don't you
send in a pull request with ideas stored in the 'resources/' folder??

Thanks for the interest!!

Steve
President
Bio::Neos
