### ISSUE TITLE
Users table in the sqlite database

### ISSUE THREAD

**Issue by sgdavis1** [bioneos/backup-system#32]
We will add a simple users table in the events database for this project. Define the structure here first before incorporating into the Sequelize models for generation. For now, we will only support user CRUD using direct DB access.

**Comment by osandvold302** [comment]
`User = {
  username : 'name',
  password : 'pass'
}`

At a minimum. Are there any other attributes that would be necessary?

**Comment by smithmf** [comment]
@sgdavis1 are we going to salt each password? Also, not sure if this is implied, but we will not actually store the password in the db, but a hash of it (i'm fine if we leave the name as `password`)

**Comment by smithmf** [comment]
Also, any thoughts on something like access levels?

**Comment by osandvold302** [comment]
we could have 2 levels of access, `1 - read only`, `2 - read & write` or instead of integers it could be `low-level` vs `high-level`

**Comment by sgdavis1** [comment]
I did some research on this topic. In the future, you can do this as well and try to identify / propose something too. I think 2018 thinking is that [Argon2](https://www.npmjs.com/package/argon2) is a good choice. My second would be [bcrypt](https://www.npmjs.com/package/bcrypt-nodejs). Either should be a good starting point.

I don't want to introduce access levels (yet). If we did, I would want a more complete implementation for `roles` I think (separate table).

Absolutely yes on the `salt`. This is a bare minimum in security standards by this day.

Here are some articles for review:
[Current thinking that points to Argon2](https://www.owasp.org/index.php/Password_Storage_Cheat_Sheet)
[Competition referenced by above](https://password-hashing.net/)
[Older summary of state of the art from 2013](https://security.blogoverflow.com/2013/09/about-secure-password-hashing/)

[Argon2 Implementation example](https://stormpath.com/blog/secure-password-hashing-in-node-with-argon2)

**Comment by osandvold302** [comment]
Added `'salt' : DataTypes.STRING` attribute for User model.

**Comment by osandvold302** [comment]
We will want a `createdAt` attribute and possibly timestamps for login activity. 

The timestamps could be an array of the last 2-3 times the user has logged in, i.e.
``` 'last_logins' = [ most_prev_date1, most_prev_date2, most_prev_date3 ]```
or it could even just be a single timestamp of the last time the user has logged in,
```'last_login' = DataTypes.STRING```

**Comment by osandvold302** [comment]
Another idea - we could change the `updatedAt` attribute to `lastLogin` and set the timestamp at each successful login.

**Comment by osandvold302** [comment]
final proposal for User model
```
User = {
'username' : 'USERNAME',
'password' : 'ARGON2HASH',
'lastLogin' : 'date of last login' (null to start),
'createdAt' : 'date of creation'
}
```
Note we do not need a `salt` region since the salt will be stored in the hash and extracted when `argon2.verify` is called.

**Comment by osandvold302** [comment]
[9275106](https://github.com/bioneos/backup-system/commit/927510659cbd263416240a5cca0216fa89ffe26c) updated User table and follows outlined model above
