### ISSUE TITLE
Login API route

### ISSUE THREAD

**Issue by sgdavis1** [bioneos/backup-system#34]
We will have a login API route that responds to requests with 200 on success and 401 on failure. The route should respond to POST messages on `/api/login` and ignore any other HTTP verbs.

**Comment by osandvold302** [comment]
First attempt to address this issue in [latest commit](https://github.com/bioneos/backup-system/commit/f23d5bd241919c8f874b74d42a3c38f660723c84). The API written will send a response for `POST` requests at `/login`.

**Comment by sgdavis1** [comment]
This cannot be complete unless #32 is done?

**Comment by osandvold302** [comment]
Ope, my bad.

**Comment by osandvold302** [comment]
For unsuccessful login attempts, the response status will be set to `401` and will send a JSON object set up as such: `{ error: 'message'}`. For successful logins, the response will be set to `200` and return `{}`

**Comment by osandvold302** [comment]
With User table in place, login API route finds a given user in the database by `username`, verifies plain-text password matches Argon2 hash, and updates `lastLogin` attribute if the login is successful.
