### ISSUE TITLE
Brainstorm dashboard components

### ISSUE THREAD

**Issue by agustafson19** [bioneos/backup-system#42]
I know the dashboard needs to have these things:
-it needs to see all the machines
-for each machine list when was the last backup
-for each machine, list the last several backups
-for each machine, list the schedule
-for each machine, list the status
-for each machine, list the backups on disk
-Title
-Logo

What else should it have?

**Comment by osandvold302** [comment]
We will want to define an object to pass to the template so that it can generate the content. This can be similar to the `emailData` object defined in `system.js` and passed to the `summary.njk` template
