### ISSUE TITLE
Error handling for util functions involving the file system

### ISSUE THREAD

**Issue by dominicrutk** [bioneos/backup-system#47]
Currently, util functions such as findDirSize, findFreeSpace, and countSubdirectoriesExclude have no error handling for the case when the directory does not exist. This means that the summary email and the dashboard pages throw errors when no backups have been made for a machine, so its directory does not yet exist.

**Comment by DominicRutkowski** [comment]
These issues can be solved by using `fs.ensureDirSync()`, but it is unnecessary to make these changes because most of this logic will change soon.

**Comment by dominicrutk** [comment]
Fixed by https://github.com/bioneos/backup-system/commit/f053ddcb46a5d57c9c883af26f0f0e8f2000e71e
