### ISSUE TITLE
Logging on routes

### ISSUE THREAD

**Issue by sgdavis1** [bioneos/backup-system#48]
Currently we use the default layout from `log4js-express` to send access requests to the log. Personally I don't agree with some of the categorizations (such as `304 Not Modified` being considered a `WARN` level entry). Additionally, I think we want to make sure this behavior doesn't clutter the logs with all the public asset requests. So we should customize this behavior for our needs (they have examples of this in their docs).

**Comment by DominicRutkowski** [comment]
Closed by https://github.com/bioneos/backup-system/commit/a8f077766a45b29fb32b9be5834cec7411bb06d1
