### ISSUE TITLE
Restrictions on `ignored_files`

### ISSUE THREAD

**Issue by sgdavis1** [bioneos/backup-system#52]
I believe the original intention on `machines/config:ignored_files[]` was to reduce potential for confusing complex configurations and for that reason we decided to restrict this setting to disallow wildcards. I believe we should revisit this decision as I don't see the problem with allowing them, especially given the way we enforce a specific order of parameters to `rsync` for this exact reason. At a minimum, we should allow the `*` and `?` wildcards to enable more complex paths that don't cross multiple directory levels.

**Comment by DominicRutkowski** [comment]
Closed by https://github.com/bioneos/backup-system/commit/e960a17ae7b53d696abb857e1fe407c67c3e9cc3
