### ISSUE TITLE
SSH host checking

### ISSUE THREAD

**Issue by sgdavis1** [bioneos/backup-system#56]
We need a better way to handle SSH host checking. If you forget to add the target backup workstation to the known hosts list, then in the default SSH configuration, Alcove will indefinitely pause when it tries to connect for the first time. 

I'm thinking we might want to add a fingerprint check that occurs at startup, and perhaps tie this to the configuration file in some way (they could either manually add the host to the config before startup, or else we could terminate early if it is missing from the `known_hosts` file. 

Something along those lines will help reduce the possibility of making this mistake (I've made it a few times now).

**Comment by DominicRutkowski** [comment]
Closed by https://github.com/bioneos/backup-system/commit/20a97d95e9253871fbae1050a3b7e465219e7607
