### ISSUE TITLE
Slack notification system

### ISSUE THREAD

**Issue by dominicrutk** [bioneos/backup-system#61]
Create a system that posts important system notifications in Slack. Allow the user to specify a webhook URL in the config file.

**Comment by DominicRutkowski** [comment]
What types of events do we want to send Slack notifications for? I think we could send notifications for successful backups for each machine and any errors.

**Comment by dominicrutk** [comment]
Basic setup in https://github.com/bioneos/backup-system/commit/87e4e9d2feb449708a9ae11803471352d3493185
