### ISSUE TITLE
Determine conditions when Promise to read the database should reject

### ISSUE THREAD

**Issue by osandvold302** [bioneos/backup-system#7]
Example:
If the sqlite query to find all backups since the last email summary returns no backups, would that be reason to reject the Promise or should it be noted in the resolve? 

Things to keep in mind:
- we will eventually want to extend this into a web app so we may want to be more conservative on what we would let be a condition to reject
- right now I have 2 promises to read 1. the most recent ProcessEvent and 2. the recent backups since the last email summary and the resolve contains the information about those events and the reject has an error message if the sqlite query returns empty

**Comment by sgdavis1** [comment]
Typically we reserve `rejection` for error cases. This isn't an error case, just a lack of backups. It is more appropriate to resolve with an empty message.

However, I believe if you are working on the summary email call you will need to check out my latest push as I completed reorganizing that code. It will be useful for you to look at and compare that to what you did as well.
